const root = {
  alternates: {
    canonical: "/",
  },
  twitter: {
    creator: "@jaykerkar0405",
    card: "summary_large_image",
  },
  openGraph: {
    images: [
      {
        sizes: "1200x630",
        type: "image/png",
        url: "https://res.cloudinary.com/bytewise0405/image/upload/v1704711959/Jay%20Kerkar/client-side/App/open_graph_dsgvmx.png",
      },
    ],
    url: "/",
    locale: "en_IN",
    type: "website",
    siteName: "CalcWeb",
    title: "CalcWeb | Jay Kerkar | Full Stack Web & Mobile App Developer",
    description:
      "I specialize in full-stack web and mobile development, passionately coding for intuitive digital experiences. Eager to connect and explore tech opportunities!",
  },
  generator: "Next.js",
  creator: "Jay Kerkar",
  publisher: "ByteWise",
  applicationName: "CalcWeb",
  category: "Design, Personal, Portfolio, Technology",
  title: "CalcWeb | Jay Kerkar | Full Stack Web & Mobile App Developer",
  metadataBase: new URL(String(process.env.NEXT_PUBLIC_BASE_URL)),
  authors: [{ name: "Jay Kerkar", url: "https://github.com/jaykerkar0405" }],
  description:
    "I specialize in full-stack web and mobile development, passionately coding for intuitive digital experiences. Eager to connect and explore tech opportunities!",
  keywords: [
    "jay",
    "Jay",
    "CSS",
    "HTML",
    "Vesit",
    "React",
    "kerkar",
    "Kerkar",
    "Node.js",
    "Next.js",
    "JayKerkar",
    "jaykerkar",
    "JavaScript",
    "jay kerkar",
    "Jay Kerkar",
    "React Native",
    "Web Development",
    "API Integration",
    "Jay Kerkar Vesit",
    "Scalable Solutions",
    "Database Management",
    "Full Stack Developer",
    "Back-End Development",
    "Responsive Web Design",
    "User Interface Design",
    "Front-End Development",
    "Mobile App Development",
    "Cross-Platform Development",
    "User Experience (UX) Design",
    "Vivekanand Education Society",
    "Vivekanand Education Society's Institute Of Technology",
  ],
};

export { root };
